apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulse-minio-external-secret
  namespace: production
  labels:
    app: pulse-minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pulse-vault-store
    kind: ClusterSecretStore
  target:
    name: pulse-minio-secret
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef: { key: pulse/minio, property: MINIO_ROOT_USER }
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef: { key: pulse/minio, property: MINIO_ROOT_PASSWORD }
    - secretKey: MINIO_ACCESS_KEY
      remoteRef: { key: pulse/minio, property: MINIO_ACCESS_KEY }
    - secretKey: MINIO_SECRET_KEY
      remoteRef: { key: pulse/minio, property: MINIO_SECRET_KEY }
