apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulse-postgresql-external-secret
  namespace: production
  labels:
    app: pulse-postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pulse-vault-store
    kind: ClusterSecretStore
  target:
    name: pulse-postgresql-secret   # exact name deployment.yaml expects
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef: { key: pulse/postgresql, property: POSTGRES_USER }
    - secretKey: POSTGRES_PASSWORD
      remoteRef: { key: pulse/postgresql, property: POSTGRES_PASSWORD }
    - secretKey: POSTGRES_DB
      remoteRef: { key: pulse/postgresql, property: POSTGRES_DB }
    - secretKey: DEBEZIUM_PASSWORD
      remoteRef: { key: pulse/postgresql, property: DEBEZIUM_PASSWORD }
