apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulse-api-external-secret
  namespace: production
  labels:
    app: pulse-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pulse-vault-store
    kind: ClusterSecretStore
  target:
    name: pulse-api-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef: { key: pulse/api, property: SECRET_KEY }
    - secretKey: GEMINI_API_KEY
      remoteRef: { key: pulse/api, property: GEMINI_API_KEY }
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef: { key: pulse/api, property: GOOGLE_CLIENT_ID }
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef: { key: pulse/api, property: GOOGLE_CLIENT_SECRET }
    - secretKey: SMTP_USER
      remoteRef: { key: pulse/api, property: SMTP_USER }
    - secretKey: SMTP_PASSWORD
      remoteRef: { key: pulse/api, property: SMTP_PASSWORD }
