apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulse-nifi-external-secret
  namespace: production
  labels:
    app: pulse-nifi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pulse-vault-store
    kind: ClusterSecretStore
  target:
    name: pulse-nifi-secret
    creationPolicy: Owner
  data:
    - secretKey: NIFI_ADMIN_USER
      remoteRef: { key: pulse/nifi, property: NIFI_ADMIN_USER }
    - secretKey: NIFI_ADMIN_PASSWORD
      remoteRef: { key: pulse/nifi, property: NIFI_ADMIN_PASSWORD }
    - secretKey: NIFI_SENSITIVE_PROPS_KEY
      remoteRef: { key: pulse/nifi, property: NIFI_SENSITIVE_PROPS_KEY }
