apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulse-airflow-external-secret
  namespace: production
  labels:
    app: pulse-airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pulse-vault-store
    kind: ClusterSecretStore
  target:
    name: pulse-airflow-secret
    creationPolicy: Owner
  data:
    - secretKey: AIRFLOW_FERNET_KEY
      remoteRef: { key: pulse/airflow, property: AIRFLOW_FERNET_KEY }
    - secretKey: AIRFLOW_SECRET_KEY
      remoteRef: { key: pulse/airflow, property: AIRFLOW_SECRET_KEY }
    - secretKey: AIRFLOW_ADMIN_USER
      remoteRef: { key: pulse/airflow, property: AIRFLOW_ADMIN_USER }
    - secretKey: AIRFLOW_ADMIN_PASSWORD
      remoteRef: { key: pulse/airflow, property: AIRFLOW_ADMIN_PASSWORD }
